/* RSS Downloader UI. The host application injects window.RSSDownloaderAPI with the platform adapter. */
(() => {
  const TABS = [["social-downloader", "Social Downloader"], ["tamil-movies", "Tamil Movies"], ["tamil-dubbed-movies", "Tamil Dubbed Movies"]];
  const PRELOADED = {
    "tamil-movies": [["Maharaja",2024],["Amaran",2024],["Lubber Pandhu",2024],["Good Night",2023],["Parking",2023],["Tourist Family",2025],["Dragon",2025],["Retro",2025]],
    "tamil-dubbed-movies": [["Kalki 2898 AD",2024],["Pushpa 2: The Rule",2024],["Hanuman",2024],["Leo",2023],["Salaar",2023],["Baahubali 2",2017],["RRR",2022],["Jailer",2023]]
  };
  const api = window.RSSDownloaderAPI;
  const tabsEl=document.querySelector("#tabs"),home=document.querySelector("#homeView"),downloads=document.querySelector("#downloadsView"),settings=document.querySelector("#settingsView");
  const urlInput=document.querySelector("#urlInput"),analyzeButton=document.querySelector("#analyzeButton"),analysisState=document.querySelector("#analysisState"),mediaOptions=document.querySelector("#mediaOptions"),movieSearchArea=document.querySelector("#movieSearchArea"),ongoingList=document.querySelector("#ongoingList"),historyList=document.querySelector("#historyList"),badge=document.querySelector("#downloadBadge");
  let currentTab=localStorage.getItem("rss-downloader-active-tab")||"social-downloader",tabOrder=loadTabOrder(),jobs=[],downloadView="ongoing",unsubscribe=null,movieSelection=null;
  function loadTabOrder(){try{const saved=JSON.parse(localStorage.getItem("rss-downloader-tab-order")||"null");if(Array.isArray(saved)&&saved.length===TABS.length&&saved.every(x=>TABS.some(t=>t[0]===x)))return saved;}catch(_){}return TABS.map(t=>t[0]);}
  function tabLabel(id){return TABS.find(t=>t[0]===id)?.[1]||id;}
  function ongoing(job){return ["queued","running","paused"].includes(job.status);}
  function esc(value){return String(value??"").replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));}
  function formatBytes(value){if(value==null)return "—";const units=["B","KB","MB","GB","TB"];let n=Number(value),i=0;while(n>=1024&&i<units.length-1){n/=1024;i++;}return `${n<10&&i?n.toFixed(1):Math.round(n)} ${units[i]}`;}
  function formatSpeed(value){return value==null?"—":`${formatBytes(value)}/s`;}
  function formatEta(value){if(value==null)return "—";const s=Math.max(0,Math.round(value));return s<60?`${s}s`:`${Math.floor(s/60)}m ${s%60}s`;}
  function applyTheme(theme){const selected=theme==="light"?"light":"dark";document.documentElement.dataset.theme=selected;localStorage.setItem("rss-downloader-theme",selected);const b=document.querySelector("#appearanceButton");if(b)b.textContent=selected==="light"?"☀":"☾";const sw=document.querySelector("#themeSwitch");if(sw)sw.checked=selected==="light";}
  function settingEnabled(key,fallback){const raw=localStorage.getItem(key);return raw===null?fallback:raw==="true";}
  function renderTabs(){tabsEl.innerHTML=tabOrder.map(id=>`<button class="tab ${id===currentTab?"active":""}" draggable="true" data-tab="${id}">${esc(tabLabel(id))}</button>`).join("");tabsEl.querySelectorAll(".tab").forEach(button=>{button.addEventListener("click",()=>selectTab(button.dataset.tab));button.addEventListener("dragstart",e=>e.dataTransfer.setData("text/plain",button.dataset.tab));button.addEventListener("dragover",e=>e.preventDefault());button.addEventListener("drop",e=>{e.preventDefault();const from=e.dataTransfer.getData("text/plain"),to=button.dataset.tab;if(from===to)return;tabOrder=tabOrder.filter(x=>x!==from);tabOrder.splice(tabOrder.indexOf(to),0,from);localStorage.setItem("rss-downloader-tab-order",JSON.stringify(tabOrder));api?.reorderTabs?.(tabOrder).catch(()=>{});renderTabs();});});}
  function showHome(){home.hidden=false;downloads.hidden=true;settings.hidden=true;}
  function selectTab(tab){currentTab=tab;movieSelection=null;localStorage.setItem("rss-downloader-active-tab",tab);showHome();renderTabs();renderTabContent();}
  function renderTabContent(){const social=currentTab==="social-downloader";urlInput.closest(".hero-card").style.display=social?"block":"none";movieSearchArea.innerHTML="";if(!social&&settingEnabled("rss-downloader-preload",true))renderMovieSearch();}
  function renderMovieSearch(){const list=PRELOADED[currentTab]||[];movieSearchArea.innerHTML=`<section class="panel"><div class="movie-heading"><div><p class="eyebrow">${esc(tabLabel(currentTab)).toUpperCase()}</p><h2>${movieSelection?"Select quality":"Pre-loaded movies"}</h2></div><span class="catalog-badge">${list.length} titles</span></div>${movieSelection?renderMovieSelection():`<div class="movie-grid">${list.map(([title,year])=>`<article class="movie-card"><div class="movie-poster"><img src="../rss-downloader-logo.png" alt="RSS Downloader"></div><div class="movie-card-body"><strong>${esc(title)}</strong><div class="meta">${year} • Authorized provider options</div><button class="secondary movie-preloaded" data-title="${esc(title)}">Get options</button></div></article>`).join("")}</div><div class="url-row movie-search-row"><input id="movieQuery" placeholder="Optional: search more movies…" autocomplete="off"><button id="movieSearchButton" class="primary">Search</button></div><div id="movieResults" class="download-list"></div>`}</section>`;if(movieSelection){document.querySelectorAll(".movie-download-option").forEach(b=>b.addEventListener("click",()=>startMovieDownload(b.dataset.option,b.dataset.request)));document.querySelector("#movieBack")?.addEventListener("click",()=>{movieSelection=null;renderMovieSearch();});return;}document.querySelectorAll(".movie-preloaded").forEach(b=>b.addEventListener("click",()=>runMovieSearch(b.dataset.title)));const input=document.querySelector("#movieQuery"),button=document.querySelector("#movieSearchButton");button.addEventListener("click",()=>runMovieSearch(input.value));input.addEventListener("keydown",e=>{if(e.key==="Enter")runMovieSearch(input.value);});}
  function renderMovieSelection(){const opts=movieSelection.mediaOptions||[];return `<div class="movie-selection"><button id="movieBack" class="secondary">← Back to movies</button><h3>${esc(movieSelection.title)}</h3>${opts.length?opts.map(o=>`<div class="option"><div><strong>${esc(o.kind.toUpperCase())}</strong><div class="meta">${esc(o.format)}${o.quality?" • "+esc(o.quality):""}${o.sizeBytes?" • "+formatBytes(o.sizeBytes):""}</div></div><button class="primary movie-download-option" data-option="${esc(o.id)}" data-request="${esc(movieSelection.requestId)}">Download</button></div>`).join(""):"<div class=\"empty\">No authorized quality options available.</div>"}</div>`;}
  async function runMovieSearch(query){const resultsEl=document.querySelector("#movieResults");query=query.trim();if(!query){resultsEl.innerHTML=`<div class="state">Choose a pre-loaded title or enter a search.</div>`;return;}resultsEl.innerHTML=`<div class="state">Searching…</div>`;try{if(!api)throw new Error("RSS Downloader host API is not connected.");const result=await api.search({tab:currentTab,query});resultsEl.innerHTML=result.results.length?result.results.map(item=>`<article class="download-card"><img class="thumb" src="${esc(item.thumbnailUrl||"../rss-downloader-logo.png")}" alt=""><div><div class="download-title">${esc(item.title)}</div><div class="meta">${item.year?esc(item.year):""} ${item.qualities?.length?"• "+esc(item.qualities.join(" / ")):""}</div></div><button class="secondary movie-select" data-id="${esc(item.id)}">Select</button></article>`).join(""):`<div class="empty">No authorized provider results found.</div>`;resultsEl.querySelectorAll(".movie-select").forEach(b=>b.addEventListener("click",()=>selectMovie(result.results.find(x=>x.id===b.dataset.id))));}catch(error){resultsEl.innerHTML=`<div class="state">${esc(error.message||error)}</div>`;}}
  function selectMovie(item){if(!item)return;movieSelection=item;if(!item.requestId||!item.mediaOptions?.length){renderMovieSearch();const panel=document.querySelector(".movie-selection");if(panel)panel.insertAdjacentHTML("beforeend",`<div class="state">This result is waiting for its authorized provider to supply download options.</div>`);return;}renderMovieSearch();}
  async function startMovieDownload(optionId,requestId){if(!api||!requestId)return;try{const job=await api.createDownload({requestId,mediaOptionId:optionId,authorizationApproved:true});movieSelection=null;home.hidden=true;downloads.hidden=false;await refreshDownloads();if(job.status==="failed"){document.querySelector("#downloadsState").hidden=false;document.querySelector("#downloadsState").textContent=job.error||"Download failed.";}}catch(error){const panel=document.querySelector(".movie-selection");if(panel)panel.insertAdjacentHTML("beforeend",`<div class="state">${esc(error.message||error)}</div>`);}}
  async function analyze(){const url=urlInput.value.trim();if(!url)return;analysisState.hidden=false;analysisState.textContent="Analyzing URL…";mediaOptions.hidden=true;try{if(!api)throw new Error("RSS Downloader host API is not connected.");const result=await api.analyzeUrl({url});analysisState.textContent=result.title||result.normalizedUrl;mediaOptions.hidden=false;mediaOptions.innerHTML=`<div class="meta">Choose an authorized format</div>`+result.mediaOptions.map(o=>`<div class="option"><div><strong>${esc(o.kind.toUpperCase())}</strong><div class="meta">${esc(o.format)}${o.quality?" • "+esc(o.quality):""}${o.sizeBytes?" • "+formatBytes(o.sizeBytes):""}</div></div><button class="primary download-option" data-request="${esc(result.requestId)}" data-option="${esc(o.id)}">Download</button></div>`).join("");mediaOptions.querySelectorAll(".download-option").forEach(b=>b.addEventListener("click",()=>startSocialDownload(b.dataset.option,b.dataset.request)));}catch(error){analysisState.textContent=error.message||String(error);}}
  async function startSocialDownload(optionId,requestId){try{if(!api)throw new Error("RSS Downloader host API is not connected.");const job=await api.createDownload({requestId,mediaOptionId:optionId,authorizationApproved:true});home.hidden=true;downloads.hidden=false;await refreshDownloads();if(job.status==="failed"){document.querySelector("#downloadsState").hidden=false;document.querySelector("#downloadsState").textContent=job.error||"Download failed.";}}catch(error){analysisState.hidden=false;analysisState.textContent=error.message||String(error);}}
  async function refreshDownloads(){if(!api){renderJobs();return;}try{jobs=(await api.listDownloads()).jobs;renderJobs();}catch(error){const state=document.querySelector("#downloadsState");state.hidden=false;state.textContent=error.message||String(error);}}
  function renderJobs(){const active=jobs.filter(ongoing).sort((a,b)=>b.updatedAt-a.updatedAt),all=[...jobs].sort((a,b)=>b.updatedAt-a.updatedAt);badge.textContent=active.length;ongoingList.innerHTML=active.length?active.map(jobCard).join(""):`<div class="empty">No ongoing downloads.</div>`;historyList.innerHTML=all.length?all.map(jobCard).join(""):`<div class="empty">No downloads yet.</div>`;document.querySelector("#historySection").style.display=downloadView==="all"?"block":"none";document.querySelectorAll(".cancel-job").forEach(b=>b.addEventListener("click",()=>cancelJob(b.dataset.id)));}
  function jobCard(job){const percent=Number.isFinite(job.progressPercent)?Math.max(0,Math.min(100,job.progressPercent)):null,meta=[job.mediaKind,job.quality,job.format].filter(Boolean).join(" • "),bytes=job.totalBytes!=null?`${formatBytes(job.downloadedBytes||0)} / ${formatBytes(job.totalBytes)}`:formatBytes(job.downloadedBytes);return `<article class="download-card"><img class="thumb" src="${esc(job.thumbnailUrl||"../rss-downloader-logo.png")}" alt=""><div><div class="download-title">${esc(job.title||job.outputName||"RSS Download")}</div><div class="meta">${esc(job.status)} • ${esc(meta||"media")} • ${esc(bytes)} • ${esc(formatSpeed(job.speedBytesPerSecond))} • ETA ${esc(formatEta(job.etaSeconds))}</div><div class="progress"><i style="width:${percent==null?0:percent}%"></i></div>${job.error?`<div class="meta">${esc(job.error)}</div>`:""}${ongoing(job)?`<button class="cancel cancel-job" data-id="${esc(job.jobId)}">Cancel</button>`:""}</div><div class="percent">${percent==null?"—":percent+"%"}</div></article>`;}
  async function cancelJob(jobId){if(!api)return;await api.cancelDownload(jobId).catch(()=>{});await refreshDownloads();}
  function showSettings(){home.hidden=true;downloads.hidden=true;settings.hidden=false;document.querySelector("#themeSwitch").checked=document.documentElement.dataset.theme==="light";document.querySelector("#clipboardSwitch").checked=settingEnabled("rss-downloader-clipboard",true);document.querySelector("#preloadSwitch").checked=settingEnabled("rss-downloader-preload",true);}
  function closeSettings(){showHome();renderTabContent();}
  async function readClipboardUrl(){if(!settingEnabled("rss-downloader-clipboard",true))return;try{let text="";if(window.AndroidClipboard?.getText)text=String(window.AndroidClipboard.getText()||"");else if(navigator.clipboard?.readText)text=await navigator.clipboard.readText();const value=text.trim();if(/^https?:\/\//i.test(value)&&value!==urlInput.value.trim()){urlInput.value=value;analyze();}}catch(_){} }
  document.querySelector("#downloadsButton").addEventListener("click",async()=>{home.hidden=true;settings.hidden=true;downloads.hidden=false;await refreshDownloads();});
  document.querySelector("#refreshDownloads").addEventListener("click",refreshDownloads);
  document.querySelectorAll(".segmented button").forEach(b=>b.addEventListener("click",()=>{downloadView=b.dataset.view;document.querySelectorAll(".segmented button").forEach(x=>x.classList.toggle("active",x===b));renderJobs();}));
  document.querySelector("#appearanceButton").addEventListener("click",()=>applyTheme(document.documentElement.dataset.theme==="light"?"dark":"light"));
  document.querySelector("#settingsButton").addEventListener("click",showSettings);document.querySelector("#closeSettings").addEventListener("click",closeSettings);
  document.querySelector("#themeSwitch").addEventListener("change",e=>applyTheme(e.target.checked?"light":"dark"));
  document.querySelector("#clipboardSwitch").addEventListener("change",e=>localStorage.setItem("rss-downloader-clipboard",String(e.target.checked)));
  document.querySelector("#preloadSwitch").addEventListener("change",e=>{localStorage.setItem("rss-downloader-preload",String(e.target.checked));showHome();renderTabContent();});
  document.querySelector("#resetTabs").addEventListener("click",()=>{tabOrder=TABS.map(t=>t[0]);localStorage.setItem("rss-downloader-tab-order",JSON.stringify(tabOrder));api?.reorderTabs?.(tabOrder).catch(()=>{});renderTabs();});
  analyzeButton.addEventListener("click",analyze);urlInput.addEventListener("keydown",e=>{if(e.key==="Enter")analyze();});
  document.addEventListener("visibilitychange",()=>{if(!document.hidden)readClipboardUrl();});setTimeout(readClipboardUrl,700);setInterval(()=>{if(!document.hidden)readClipboardUrl();},1500);
  if(api?.getEventBus)unsubscribe=api.getEventBus().subscribe(event=>{const i=jobs.findIndex(j=>j.jobId===event.job.jobId);if(i>=0)jobs[i]=event.job;else jobs.push(event.job);renderJobs();});
  applyTheme(localStorage.getItem("rss-downloader-theme")||"dark");renderTabs();renderTabContent();renderJobs();window.addEventListener("beforeunload",()=>unsubscribe?.());
})();
